### ISSUE TITLE
Replace Wifi-router 

### ISSUE THREAD

**Issue by Jaknil** [robotikklinja/3d-printere#2]
Husk å velge ut en wifi-router så vi får bestilt inn egen så vi kan returnere den vi lånt fra 3DE.
Vi ønsker å bestille den med leveranse fra en bedrift med nettbutikk.
Du kan se på sider som elkjøp og lignende og lese kunde-tilbakemeldinger. Du kan også kolle prisjakt.no for å finne andre butikker. Jeg tenker at vi ønsker noe med 5GHz støtte men uten en masse andre spesialfunksjoner som innebygd brannmur siden de har en tendens til å gjøre ting vanskeligere.

**Comment by Falsera** [comment]
Har lagt til en bestilling for en asus router i bestillinger.
