### ISSUE TITLE
Mer plastikk?

### ISSUE THREAD

**Issue by Jaknil** [robotikklinja/3d-printere#4]
Jeg ser at vi snart gå tom på sølv-plastikk til 3D printerne. Har vi mer liggende eller er det dags å bestille inn mer? Finnes det noe material som vi ønsker å teste? Jeg foreslår at dere finner ut hva vi trenger å bestille innen vi går tom.

Min rekommandasjon: Se på https://3dnet.no/collections/1-75

Bonus rekommandasjon før å printe julegaver og pynt: Proto-pasta ger en veldig kul look https://3dnet.no/collections/1-75/products/proto-pasta-htpla-wonder-blue-1-75

Husk! Hvis dere ønsker at vi bestiller inn spesial-materialer (alt annet en PLA) så må dere lage en regel for hvem som kan bruke det, i hvilken printer og rutiner for material-bytte.

**Comment by TheWaifu27** [comment]
Har funnet en norsk nettside vi kan bruke: https://3dnet.no/collections/1-75/products/pla-1-75 . her har de mange forskjellige farger som vi kan bestille og disse passer perfekt til mk3s-ene våre.

**Comment by Jaknil** [comment]
Etter SMS-konversasjon med Ludvic så har jeg nå sent behovsmedling på 3*3kg PLA rull fra 3DNet i hvit, grå og sort farge. 
![image](https://user-images.githubusercontent.com/3476653/70727901-c32e0500-1d00-11ea-94bd-3ac9a5a35aa5.png)

**Comment by Jaknil** [comment]
Fun fact! Man kan stille inn så man ser printing-pris i PrusaSlicer, trur det går i Cura også. Det virker koste cirka 8 kr / time.
